// Generated by CoffeeScript 1.6.3
var fs;

fs = require('fs');

module.exports = function(config) {
  var handle, path;
  if ('string' === typeof config) {
    path = config;
  }
  handle = function(_arg, callback) {
    var client, error, rest, uuid;
    rest = _arg.rest;
    try {
      if (uuid = rest[0]) {
        client = require(path);
        return callback(null, {
          headers: {
            'Content-Type': 'text/javascript'
          },
          body: "(\n" + (client.toString()) + "\n)('" + uuid + "');\n"
        });
      }
    } catch (_error) {
      error = _error;
      return callback(null, {
        statusCode: 404
      });
    }
    return callback(null, {
      headers: {
        'Content-Type': 'text/html'
      },
      body: "\n<head></head>\n<body>\n\n    <script src='resources/build.js'></script>\n    <script src='main/UUID'></script>\n\n</body>\n"
    });
  };
  handle.$www = {};
  return handle;
};
