// Generated by CoffeeScript 1.6.3
var fs;

fs = require('fs');

module.exports = function(config) {
  var handle, path;
  if ('string' === typeof config) {
    path = config;
  }
  handle = function(_arg, callback) {
    var arg1, arg2, arg3, client, error, rest;
    rest = _arg.rest;
    try {
      if (rest[0] === 'js') {
        arg1 = ((function() {
          try {
            return rest[1];
          } catch (_error) {}
        })()) || '';
        arg2 = ((function() {
          try {
            return rest[2];
          } catch (_error) {}
        })()) || '';
        arg3 = ((function() {
          try {
            return rest[3];
          } catch (_error) {}
        })()) || '';
        client = ((function() {
          try {
            return require(path);
          } catch (_error) {}
        })()) || function() {
          return alert('client not found!');
        };
        return callback(null, {
          headers: {
            'Content-Type': 'text/javascript'
          },
          body: "(\n" + (client.toString()) + "\n)('" + arg1 + "','" + arg2 + "','" + arg3 + "');\n"
        });
      }
    } catch (_error) {
      error = _error;
      return callback(null, {
        statusCode: 404
      });
    }
    return callback(null, {
      headers: {
        'Content-Type': 'text/html'
      },
      body: "\n<head></head>\n<body>\n\n    <script src='build/build.js'></script>\n    <script src='main/js'></script>\n\n</body>\n"
    });
  };
  handle.$www = {};
  return handle;
};
