// Generated by CoffeeScript 1.6.3
module.exports = function(config) {
  var handle;
  console.log({
    config: config
  });
  handle = function(opts, callback) {
    console.log({
      opts: opts
    });
    return callback(null, {
      main: 1
    });
  };
  handle.$www = {};
  return handle;
};
